version: '3.2'
services:
  postgres:
    image: 'postgres:12'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nenamagermassage
    ports:
      - '5432:5432'
    volumes:
      - ./.volumes/postgres:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:
    name: docker-private-network
